In [2]:
import exposal as E
import pandas as pd

In [2]:
E.getViews()

['Humerus',
 'SCAPULAR',
 'Calcaneus',
 'SACRUM',
 'OPTIC ',
 'Mandible',
 'Sternum',
 'L-SPINE',
 'KNEE',
 'Elbow',
 'NECK',
 'RIB',
 'T-SPINE',
 'SHOULDER',
 'CLAVICLE',
 'TIBIA',
 'Ankle',
 'SKULL',
 'FINGER',
 'Zygoma',
 'PELVIS',
 'FOOT',
 'Hand',
 'C-SPINE',
 'HIP',
 'COCCYX',
 'Wrist',
 'ABD',
 'CHEST',
 'T.M Joint',
 'Mastoid',
 'P.N.S',
 'NASAL',
 'FUMUR']

In [6]:
E.getPositions('CHEST')

['PED PA', 'PED LAT', 'PA', 'Decubitus', 'LAT']

In [3]:
exp=E.getExposal('CHEST', 'PED LAT')

In [6]:
exp['ma']*exp['msec']/1000

8.0

In [7]:
exp

{'kvp': 95, 'ma': 320, 'msec': 25.0, 'mas': 8.0}

In [2]:
import numpy as np
import cv2
from matplotlib import pyplot as plt

In [3]:
def pause():
    keyCode=cv2.waitKey(0)
    if keyCode==27:
        cv2.destroyAllWindows()

In [65]:
img=cv2.imread('img.jpg')
org=img
img=cv2.bitwise_not(img)
img=cv2.resize(img, (600,600))
img=cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
img[:,:200]=255
img[:,400:]=255
_, img=cv2.threshold(img, 70, 255, cv2.THRESH_BINARY)
contours, _=cv2.findContours(img, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)

cv2.imshow('img',img)
pause()

In [66]:
org=cv2.resize(org, (600,600))

img_contour=cv2.drawContours(org, contours, -1, (0,0,150), 2)
cv2.imshow('img_contour', img_contour)
pause()


In [34]:
contours

[array([[[584, 391]]], dtype=int32),
 array([[[575, 391]]], dtype=int32),
 array([[[578, 387]]], dtype=int32),
 array([[[594, 385]],
 
        [[594, 386]],
 
        [[594, 387]],
 
        [[594, 388]],
 
        [[593, 389]],
 
        [[594, 389]],
 
        [[595, 389]],
 
        [[596, 389]],
 
        [[597, 389]],
 
        [[598, 389]],
 
        [[599, 388]],
 
        [[599, 387]],
 
        [[598, 387]],
 
        [[597, 387]],
 
        [[596, 387]],
 
        [[595, 386]],
 
        [[596, 385]],
 
        [[595, 386]]], dtype=int32),
 array([[[584, 385]],
 
        [[584, 386]],
 
        [[584, 387]],
 
        [[583, 388]],
 
        [[582, 387]],
 
        [[581, 388]],
 
        [[582, 388]],
 
        [[583, 388]],
 
        [[584, 388]],
 
        [[585, 389]],
 
        [[586, 388]],
 
        [[587, 388]],
 
        [[588, 388]],
 
        [[589, 387]],
 
        [[590, 388]],
 
        [[590, 389]],
 
        [[591, 388]],
 
        [[591, 387]],
 
        [[59

In [33]:
a=[1,56,4,8,14,8,6,3,4,87,63,98,32,4,5,6]
a


0